#!/usr/bin/env bash
set -euo pipefail

openwisp-qa-check \
  --skip-checkmigrations \
  --skip-checkmakemigrations \
  --skip-checkcommit \
  --skip-flake8 \
  --skip-isort \
  --skip-black \
  --skip-checkrst \
  --csslinter \
  --jslinter
npm test
